FROM microsoft/dotnet:2-sdk-jessie AS build-env
WORKDIR /app

COPY *.sln ./
COPY SimpleNetCoreApi_Test/SimpleNetCoreApi_Test.csproj SimpleNetCoreApi_Test/
RUN dotnet restore

ENTRYPOINT ["dotnet", "test", "SimpleNetCoreApi_Test.dll"]
